# Define the objects to be evualated against defined rules

config:
  # define whether to use defined objects or generate them randomly
  - generate_objects: true
  - objects_to_generate: 100

objects:
  shapes:
    - colour: [red, green]
      shape: rectangle
      size: large

    - colour: green
      shape: circle
      size: small

  cars:
    - colour: grey
      size: small
      doors: 3

    - colour: black
      size: large
      doors: 5
